### ISSUE TITLE
Deployment Issue: failed to verify artifact in SupplyChain Example

### ISSUE THREAD

**Issue by Prajval108** [hyperledger/bevel-samples#21]
failed to verify artifact: computed checksum 'e271f3ebff201e301f705bd5e29c267760a89ee7d92b8c002f554d88800c2c5e' doesn't match advertised '9f1b6ab0f6ae006a6fe153a32c9eca4626cfdad3684bae98bf730ee68a49788e'

**To Reproduce**
1. Deploy the network (using site.yaml) with five organisation with none proxy (ansible-playbook  platforms/shared/configuration/site.yaml -e "@./build/network.yaml")
2. Maintaining separate repo for bevel and bevel samples
3. Deploy supplychain app example (ansible-playbook examples/supplychain-app/configuration/deploy-supplychain-app.yaml -e "@./build/network_sample.yaml")
4. Playbook script stuck at "Wait for Pod manufacturer-expressapi in manufacturer-net"
5. See the error from each and every organisation namespace in events(lens)

**Expected behavior**
Supplychain example should be up and running at this stage of time

**Screenshots**
![image](https://user-images.githubusercontent.com/84852951/231455645-53a8854f-5c83-48ea-9a76-07bfe8e0fa96.png)
![image](https://user-images.githubusercontent.com/84852951/231455912-804bac04-d490-47f4-b920-6b64d899ccdf.png)

**Environment:**
 - OS: macOS 
 - Version: 13.0.1 (22A400)

**Additional context**
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af

**Comment by sownak** [comment]
@Prajval108 The checksum error is a secondary error, please check other errors for the helmrelease.

**Comment by sownak** [comment]
Closed as no updates and not an issue
